### ISSUE TITLE
Ableton 9.6 ships Python 2.7

### ISSUE THREAD

**Issue by egasimus** [gluon/AbletonLive9_RemoteScripts#29]
Just heard that announcement a few days ago. How much does this change things in practice?

**Comment by MistaTwista** [comment]
Yesterday I'm totally broke my Ableton Midi scripts. Now i know why :)

**Comment by MistaTwista** [comment]
I [decompiled](https://github.com/Mysterie/uncompyle2) new .pyc files, and there is no const.pyc for changing scales :(
